Ensure cargo arguments are added before '--'
Otherwise running a single test from vscode fails with
```
error: Unrecognized option: 'message-format'
```